import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  alternates: { canonical: "/terms" },
  openGraph: {
    title: "Terms of Service",
    description: "Terms of Service for Elvyy.",
    url: "https://elvyy.com/terms",
  },
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-2xl px-6 py-16">
      <p className="font-mono text-xs uppercase tracking-wide text-sage-deep">Legal</p>
      <h1 className="mt-2 font-display text-4xl text-ink">Terms of Service</h1>
      <p className="mt-4 text-sm text-ink-soft">Last updated: September 2026</p>

      <div className="mt-8 space-y-6 text-[16px] leading-relaxed text-ink-soft">
        <section>
          <h2 className="font-display text-xl text-ink">Acceptance of terms</h2>
          <p className="mt-2">By accessing or using Elvyy, including any tool, calculator, or article on this site, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, please do not use the site.</p>
        </section>

        <section>
          <h2 className="font-display text-xl text-ink">Use of this site</h2>
          <p className="mt-2">Elvyy's tools and articles are provided free of charge for general, informational, and everyday use. By using this site, you agree not to misuse any tool, attempt to disrupt the service, probe for vulnerabilities, scrape content for unauthorized redistribution, or use any AI powered tool to generate content that violates applicable law. You are responsible for how you use any output generated by this site, including AI generated content.</p>
        </section>

        <section>
          <h2 className="font-display text-xl text-ink">No warranty</h2>
          <p className="mt-2">Tools and calculators on this site, including the GPA Calculator, Final Grade Calculator, Study Plan Spreader, and Task Splitter, are provided for general, informational purposes only. While we aim for accuracy, results should not be relied on for medical, legal, financial, academic, or other professional decisions without independent verification. AI generated content, including meta descriptions, titles, and blog drafts, may occasionally contain inaccurate information and should be reviewed before use.</p>
        </section>

        <section>
          <h2 className="font-display text-xl text-ink">Limitation of liability</h2>
          <p className="mt-2">To the fullest extent permitted by law, Elvyy and its operator shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of, or inability to use, this site or any tool on it, including but not limited to lost data, lost academic or financial outcomes, or reliance on any calculation or AI generated output. The site and all tools are provided on an as is and as available basis, without warranties of any kind, either express or implied.</p>
        </section>

        <section>
          <h2 className="font-display text-xl text-ink">Intellectual property</h2>
          <p className="mt-2">All articles, tool interfaces, and original content on Elvyy are the property of Elvyy and its operator unless otherwise noted, and may not be reproduced, republished, or redistributed elsewhere without permission. Content you generate using any tool on this site, such as an AI generated blog draft or a QR code, belongs to you to use as you see fit.</p>
        </section>

        <section>
          <h2 className="font-display text-xl text-ink">Third party services</h2>
          <p className="mt-2">Some tools on this site rely on third party services, including AI providers and font or rendering services, to function. Elvyy is not responsible for outages, errors, or changes in these third party services that may temporarily affect tool availability.</p>
        </section>

        <section>
          <h2 className="font-display text-xl text-ink">Termination and suspension</h2>
          <p className="mt-2">We reserve the right to suspend or restrict access to this site, in whole or in part, for any user found to be misusing any tool, attempting to disrupt the service, or violating these terms, without prior notice. Since this site does not require an account, termination generally takes the form of blocking access from a specific source rather than closing an account.</p>
        </section>

        <section>
          <h2 className="font-display text-xl text-ink">Governing law and jurisdiction</h2>
          <p className="mt-2">These terms are governed by and construed in accordance with the laws of Pakistan, without regard to conflict of law principles. Any dispute arising from your use of this site shall be subject to the exclusive jurisdiction of the courts located in Pakistan, except where local consumer protection law in your country of residence provides otherwise.</p>
        </section>

        <section>
          <h2 className="font-display text-xl text-ink">Changes to these terms</h2>
          <p className="mt-2">These terms may be updated from time to time as the site grows or as applicable law changes. The date at the top of this page reflects the most recent update. Continued use of the site after a change means you accept the updated terms.</p>
        </section>

        <section>
          <h2 className="font-display text-xl text-ink">Contact</h2>
          <p className="mt-2">Questions about these terms can be sent to hajabatool01@gmail.com.</p>
        </section>
      </div>
    </div>
  );
}
